@{
    RootModule           = 'Hephaestus.psm1'
    ModuleVersion        = '0.1.0'
    GUID                 = '9be61a01-0b74-4832-867d-f2b7cb51cf85'
    Author               = 'Itamartz'
    CompanyName          = 'Hephaestus Deployment Toolkit'
    Copyright            = '(c) 2026 Itamartz. All rights reserved.'
    Description          = 'Hephaestus Deployment Toolkit - a PowerShell replacement for MDT.'

    # The engine runs inside WinPE, which only ships Windows PowerShell 5.1.
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Desktop', 'Core')

    # Explicit, never a wildcard - the export list is a contract (DESIGN 15.1).
    FunctionsToExport    = @(
        'Clear-HDTAutoLogon',
        'Add-HDTBootImageComponent',
        'Add-HDTBootImageContent',
        'Add-HDTBootImageStartCommand',
        'Remove-HDTBootImageComponent',
        'Remove-HDTBootImageContent',
        'Move-HDTBootImageStartCommand',
        'Remove-HDTBootImageStartCommand',
        'Set-HDTBootImageBackground',
        'Set-HDTBootImageDriver',
        'Set-HDTBootImageUnattend',
        'New-HDTBootImageUnattend',
        'Add-HDTBootImageCertificate',
        'Remove-HDTBootImageCertificate',
        'Set-HDTBootImageClientCertificate',
        'Set-HDTBootImageCertificatePassword',
        'Get-HDTBootImageCertificatePassword',
        'Test-HDTBootImageCertificatePassword',
        'Set-HDTWorkspaceProperty',
        'Save-HDTWorkspaceDocument',
        'Get-HDTAdkComponent',
        'Get-HDTAdkPath',
        'Get-HDTApplication',
        'Get-HDTBootImageComponent',
        'Get-HDTBootstrapConfiguration',
        'ConvertTo-HDTDiskLayout',
        'ConvertTo-HDTReport',
        'Copy-HDTLog',
        'Export-HDTMachineFact',
        'Export-HDTVariableProvenance',
        'Get-HDTAutoLogonState',
        'Get-HDTDriverGroup',
        'Get-HDTDiskLayout',
        'Get-HDTLogPath',
        'Get-HDTMachineFact',
        'Get-HDTMachineOverride',
        'Get-HDTModuleVersion',
        'Get-HDTNetworkConfiguration',
        'Get-HDTOperatingSystem',
        'Get-HDTShareAccessRule',
        'Get-HDTShareCredential',
        'Get-HDTNoOpStepDescription',
        'Get-HDTSetVariableStepDescription',
        'Get-HDTPowerShellStepDescription',
        'Get-HDTCommandLineStepDescription',
        'Get-HDTRestartStepDescription',
        'Get-HDTValidateStepDescription',
        'Get-HDTDiskPartitionStepDescription',
        'Get-HDTEnableBitLockerStepDescription',
        'Get-HDTInstallApplicationsStepDescription',
        'Get-HDTInstallRolesStepDescription',
        'Get-HDTApplyImageStepDescription',
        'Get-HDTApplyUnattendStepDescription',
        'Get-HDTConfigureBootStepDescription',
        'Get-HDTNoOpStepTemplate',
        'Get-HDTSetVariableStepTemplate',
        'Get-HDTPowerShellStepTemplate',
        'Get-HDTCommandLineStepTemplate',
        'Get-HDTRestartStepTemplate',
        'Get-HDTValidateStepTemplate',
        'Get-HDTDiskPartitionStepTemplate',
        'Get-HDTEnableBitLockerStepTemplate',
        'Get-HDTInstallApplicationsStepTemplate',
        'Get-HDTInstallRolesStepTemplate',
        'Get-HDTApplyImageStepTemplate',
        'Get-HDTApplyUnattendStepTemplate',
        'Get-HDTConfigureBootStepTemplate',
        'Get-HDTStepDescription',
        'Get-HDTSequenceTemplate',
        'Get-HDTGatherStepDescription',
        'Get-HDTGatherStepTemplate',
        'Invoke-HDTGatherStep',
        'Get-HDTInstallCertificateStepDescription',
        'Get-HDTInstallCertificateStepTemplate',
        'Invoke-HDTInstallCertificateStep',
        'Get-HDTStepType',
        'Get-HDTGroupTemplate',
        'Get-HDTUsableAddress',
        'Get-HDTVariableMap',
        'Get-HDTWizardCredential',
        'Get-HDTWizardField',
        'Get-HDTWizardHarvest',
        'Format-HDTProgressLine',
        'Get-HDTDeploymentProgress',
        'Get-HDTWizardPage',
        'Get-HDTWizardSequence',
        'Get-HDTWizardSkip',
        'Get-HDTWizardSummary',
        'Get-HDTWorkspacePath',
        'Get-HDTVariableProvenance',
        'Hide-HDTShellWindow',
        'Import-HDTApplication',
        'Import-HDTBootImageToWds',
        'Import-HDTOperatingSystem',
        'Import-HDTRuleDocument',
        'Import-HDTRunState',
        'Import-HDTSequenceDocument',
        'Import-HDTStepModule',
        'Import-HDTWizardDocument',
        'Import-HDTWorkspaceDocument',
        'Invoke-HDTNoOpStep',
        'Invoke-HDTSetVariableStep',
        'Invoke-HDTPowerShellStep',
        'Invoke-HDTCommandLineStep',
        'Invoke-HDTRestartStep',
        'Invoke-HDTValidateStep',
        'Invoke-HDTDiskPartitionStep',
        'Invoke-HDTEnableBitLockerStep',
        'Invoke-HDTInstallApplicationsStep',
        'Invoke-HDTInstallRolesStep',
        'Invoke-HDTApplyImageStep',
        'Invoke-HDTApplyUnattendStep',
        'Invoke-HDTConfigureBootStep',
        'Invoke-HDTBootReconciliation',
        'Invoke-HDTStep',
        'Invoke-HDTTaskSequence',
        'New-HDTBootImageService',
        'New-HDTCimProvider',
        'New-HDTBootIso',
        'New-HDTBuildProgress',
        'New-HDTClock',
        'New-HDTContentProvider',
        'New-HDTDeploymentPassword',
        'New-HDTDiskLayoutPlan',
        'New-HDTDiskService',
        'New-HDTEnvironmentProvider',
        'New-HDTExecutionContext',
        'New-HDTBitLockerService',
        'New-HDTFeatureService',
        'New-HDTFileSystem',
        'New-HDTImageService',
        'New-HDTLocalContentProvider',
        'New-HDTLogContext',
        'New-HDTLsaService',
        'New-HDTPowerService',
        'New-HDTProcessService',
        'New-HDTPxePayload',
        'New-HDTRegistryService',
        'New-HDTRunState',
        'New-HDTScriptInvoker',
        'New-HDTSmbContentProvider',
        'New-HDTSmbService',
        'New-HDTWizardHost',
        'New-HDTWdsService',
        'New-HDTServiceCatalog',
        'New-HDTStepResult',
        'New-HDTTaskSequence',
        'New-HDTWorkspace',
        'Resolve-HDTApplicationOrder',
        'Resolve-HDTDeployRoot',
        'Resolve-HDTImageIndex',
        'Resolve-HDTVariable',
        'Save-HDTRunState',
        'Select-HDTTargetDisk',
        'Set-HDTApplication',
        'Set-HDTAutoLogon',
        'Set-HDTLogPath',
        'Set-HDTShareCredential',
        'Set-HDTStaticAddress',
        'Show-HDTWizard',
        'Show-HDTWizardShell',
        'New-HDTConsoleProgressHost',
        'New-HDTProgressHost',
        'Split-HDTAccountName',
        'Start-HDTCommandPrompt',
        'Start-HDTProgressDisplay',
        'Step-HDTWizardPage',
        'Test-HDTApplicationDetection',
        'Test-HDTComputerName',
        'Test-HDTRunStateAbandoned',
        'Test-HDTShareAcl',
        'Test-HDTPowerShellStepApplicable',
        'Test-HDTStepApplicable',
        'Test-HDTStepCondition',
        'Test-HDTTaskSequence',
        'Update-HDTBootImage',
        'Update-HDTProgressDisplay',
        'Update-HDTRunStateStep',
        'Write-HDTLog',
        'Write-HDTStatus',
        'Write-HDTVariableLog',
        'Add-HDTStep',
        'Add-HDTStepPartition',
        'Set-HDTStepPartition',
        'Remove-HDTStepPartition',
        'Move-HDTStepPartition',
        'Copy-HDTStep',
        'Move-HDTStep',
        'Remove-HDTStep',
        'Save-HDTSequenceDocument',
        'Set-HDTStepCondition',
        'Set-HDTStepFlag',
        'Set-HDTStepProperty',

        # AUTHORING RULES.YAML, the same way and for the same reasons. Position
        # is semantics in a rules document - first match wins per variable - so
        # Add-HDTRule takes -After and -First rather than only appending.
        'Add-HDTRule',
        'Remove-HDTRule',
        'Save-HDTRuleDocument',
        'Set-HDTRule',

        # THE ADMIN CONSOLE, FOLDED IN. The WPF console is not a module, it is one
        # command: everything the window does has to run an actual HDT command, and
        # if the command does not exist the window cannot do it. Shipping it beside
        # the engine rather than beside a second manifest is what makes that true -
        # one Import-Module puts the console and the commands it invokes in the
        # same session.
        'Get-HDTConsoleBootImageSetting',
        'Get-HDTConsoleConditionOption',
        'Show-HDTBootImageWindow',
        'Show-HDTBuildProgressWindow',
        'Get-HDTConsoleClosePrompt',
        'Get-HDTConsoleEditorState',
        'Get-HDTConsoleImageChoice',
        'Get-HDTConsoleNewSequence',
        'Test-HDTConsoleNewSequence',
        'Get-HDTConsoleMonitor',
        'Get-HDTConsolePartitionRow',
        'Get-HDTConsoleMonitorNode',
        'Get-HDTConsoleSequenceEditor',
        'Get-HDTConsoleStepCatalog',
        'Get-HDTConsoleStepChange',
        'Get-HDTConsoleStepOption',
        'Get-HDTConsoleSetting',
        'Get-HDTConsoleTheme',
        'Get-HDTConsoleValidateCheck',
        'Get-HDTConsoleTreeNode',
        'Get-HDTConsoleWorkspace',
        'New-HDTConsoleHost',
        'New-HDTConsoleScreen',
        'Resolve-HDTConsoleCloseAnswer',
        'Save-HDTConsoleSetting',
        'Show-HDTConsole',
        'Show-HDTSequenceEditor'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()

    PrivateData          = @{
        PSData = @{
            Tags = @('MDT', 'Deployment', 'OSD', 'WinPE')
        }
    }
}
